### ISSUE TITLE
maven_artifact:

### ISSUE THREAD

**Issue by bbaassssiiee** [balazsmaria/skeleton#1]
Ansible has a specific module to resolve artifacts from Nexus, why not use it?

```
- name: Download JAR File to the skeleton directory
  maven_artifact:
    group_id: com.edudoo.skeleton
    artifact_id:backend
    extension: jar
    repository_url: "{{ repository_url }}"
    dest: /opt/skeleton/
    mode: 0755
```
